// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf6jYE_10FSmOzZJ6xON7JskiGUW5L94w',
    appId: '1:801641790340:web:7252df7a0301dbb426fbd1',
    messagingSenderId: '801641790340',
    projectId: 'prescriptionmanagement-21537',
    authDomain: 'prescriptionmanagement-21537.firebaseapp.com',
    storageBucket: 'prescriptionmanagement-21537.firebasestorage.app',
    measurementId: 'G-4M088ET08B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcTBj3WtrZ1UDRv1EG4XzqZ-1Ommum1JI',
    appId: '1:801641790340:android:6c1824c9b2efecc726fbd1',
    messagingSenderId: '801641790340',
    projectId: 'prescriptionmanagement-21537',
    storageBucket: 'prescriptionmanagement-21537.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBriXjLzSoA2jfYjeKPmQN7PDm_fTXdeL0',
    appId: '1:801641790340:ios:cf010351d3e1776f26fbd1',
    messagingSenderId: '801641790340',
    projectId: 'prescriptionmanagement-21537',
    storageBucket: 'prescriptionmanagement-21537.firebasestorage.app',
    iosBundleId: 'com.example.healthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBriXjLzSoA2jfYjeKPmQN7PDm_fTXdeL0',
    appId: '1:801641790340:ios:cf010351d3e1776f26fbd1',
    messagingSenderId: '801641790340',
    projectId: 'prescriptionmanagement-21537',
    storageBucket: 'prescriptionmanagement-21537.firebasestorage.app',
    iosBundleId: 'com.example.healthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf6jYE_10FSmOzZJ6xON7JskiGUW5L94w',
    appId: '1:801641790340:web:157a0f80241deeaf26fbd1',
    messagingSenderId: '801641790340',
    projectId: 'prescriptionmanagement-21537',
    authDomain: 'prescriptionmanagement-21537.firebaseapp.com',
    storageBucket: 'prescriptionmanagement-21537.firebasestorage.app',
    measurementId: 'G-J21Z3XSZRG',
  );
}
